name: Deploy to Ubuntu

on:
  push:
    branches:
      - main  

jobs:
  build-and-deploy-locally:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Docker
      uses: docker/setup-buildx-action@v3
      
      with:
        dockerfile: Dockerfile

    - name: Build Docker image
      run: |
        docker build -t isecimg .
        
    - name: Export image
      run: docker save -o isec.tar.gz isecimg

    - name: install ssh keys

      run: |
        mkdir -p ~/.ssh
        echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
        chmod 600 ~/.ssh/id_rsa
        ssh-keyscan -H ${{ secrets.VPS_IP }} >> ~/.ssh/known_hosts
        chmod 644 ~/.ssh/known_hosts

 #   - name: Login to VPS
 #    run: ssh ubuntu@${{ secrets.VPS_IP }}

    - name: Copy Docker image to VPS
      run: sudo scp  -o StrictHostKeyChecking=no -i ~/.ssh/id_rsa  isec.tar.gz ubuntu@${{ secrets.VPS_IP }}:/home/ubuntu/remoteBuilds/

    - name: Login to VPS and run docker
      run: |
        ssh ubuntu@${{ secrets.VPS_IP }} "
          sudo docker load -i /home/ubuntu/remoteBuilds/isec.tar.gz &&
          sudo docker stop isecimgContainer || true &&
          sudo docker rm isecimgContainer || true &&
          sudo docker run \
            -e BASE_URL=https://isec.bhashith.me/ \
            -e DB_URL=${{ secrets.DB_URL }} \
            -e PORT=${{ secrets.PORT }} \
            -e AUTH0_ISSUER_BASE_URL=${{ secrets.AUTH0_ISSUER_BASE_URL }} \
            -e AUTH0_CLIENT_ID=${{ secrets.AUTH0_CLIENT_ID }} \
            -e SESSION_SECRET=${{ secrets.SESSION_SECRET }} \
            -e AUTH0_MGMT=${{ secrets.AUTH0_MGMT }} \
            -e SERVER_RESTART_TIMEOUT=${{ secrets.SERVER_RESTART_TIMEOUT }} \
            -e NODE_ENV=${{ secrets.NODE_ENV }} \
            -e HCAPTCHA_SITE_KEY=${{ secrets.HCAPTCHA_SITE_KEY }} \
            -e HCAPTCHA_SEC_KEY=${{ secrets.HCAPTCHA_SEC_KEY }} \
            -d --name isecimgContainer -p 6969:8080 isecimg &&
          exit"

        
    - name: cleanup
      run: rm -rf ~/.ssh
