name: Deploy to Ubuntu

on:
  push:
    branches:
      - main  

jobs:
  build-and-deploy-locally:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Docker
      uses: docker/setup-buildx-action@v3
      
      with:
        dockerfile: Dockerfile

    - name: Build Docker image
      run: docker build -t isecimg .

    - name: install ssh keys

      run: |
            install -m 600 -D /dev/null ~/.ssh/id_rsa
            echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
            ssh-keyscan -H 35.87.98.80 > ~/.ssh/known_hosts

 #   - name: Login to VPS
 #    run: ssh ubuntu@35.87.98.80

    - name: Copy Docker image to VPS
      run: sudo scp  -o StrictHostKeyChecking=no -i ~/.ssh/id_rsa  isecimg.tar.gz ubuntu@35.87.98.80:/home/ubuntu/remoteBuilds/
      
    - name: Login to VPS
      run: ssh ubuntu@35.87.98.80

    - name: Load Docker image on VPS
      run: docker load -i /home/ubuntu/remoteBuilds/isecimg.tar.gz

    - name: Stop existing Docker container on VPS
      run: docker stop isecimgContainer || true

    - name: Remove existing Docker container on VPS
      run: docker rm isecimgContainer || true

    - name: Run Docker container on VPS
      run: docker run -d --name isecimgContainer -p 6969:8080 isecimg

    - name: Exit SSH
      run: exit

    - name: cleanup
      run: rm -rf ~/.ssh
